# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bar/Downloads/anonymizer/Anonymizer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bar/Downloads/anonymizer/Anonymizer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bar/Downloads/anonymizer/Anonymizer/CMakeFiles /home/bar/Downloads/anonymizer/Anonymizer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bar/Downloads/anonymizer/Anonymizer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named anonymizer

# Build rule for target.
anonymizer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 anonymizer
.PHONY : anonymizer

# fast build rule for target.
anonymizer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/build
.PHONY : anonymizer/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

compiled/http_log.capnp.o: compiled/http_log.capnp.c++.o
.PHONY : compiled/http_log.capnp.o

# target to build an object file
compiled/http_log.capnp.c++.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/compiled/http_log.capnp.c++.o
.PHONY : compiled/http_log.capnp.c++.o

compiled/http_log.capnp.i: compiled/http_log.capnp.c++.i
.PHONY : compiled/http_log.capnp.i

# target to preprocess a source file
compiled/http_log.capnp.c++.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/compiled/http_log.capnp.c++.i
.PHONY : compiled/http_log.capnp.c++.i

compiled/http_log.capnp.s: compiled/http_log.capnp.c++.s
.PHONY : compiled/http_log.capnp.s

# target to generate assembly for a file
compiled/http_log.capnp.c++.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/compiled/http_log.capnp.c++.s
.PHONY : compiled/http_log.capnp.c++.s

src/HttpLog.o: src/HttpLog.cpp.o
.PHONY : src/HttpLog.o

# target to build an object file
src/HttpLog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/src/HttpLog.cpp.o
.PHONY : src/HttpLog.cpp.o

src/HttpLog.i: src/HttpLog.cpp.i
.PHONY : src/HttpLog.i

# target to preprocess a source file
src/HttpLog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/src/HttpLog.cpp.i
.PHONY : src/HttpLog.cpp.i

src/HttpLog.s: src/HttpLog.cpp.s
.PHONY : src/HttpLog.s

# target to generate assembly for a file
src/HttpLog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/src/HttpLog.cpp.s
.PHONY : src/HttpLog.cpp.s

src/HttpSender.o: src/HttpSender.cpp.o
.PHONY : src/HttpSender.o

# target to build an object file
src/HttpSender.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/src/HttpSender.cpp.o
.PHONY : src/HttpSender.cpp.o

src/HttpSender.i: src/HttpSender.cpp.i
.PHONY : src/HttpSender.i

# target to preprocess a source file
src/HttpSender.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/src/HttpSender.cpp.i
.PHONY : src/HttpSender.cpp.i

src/HttpSender.s: src/HttpSender.cpp.s
.PHONY : src/HttpSender.s

# target to generate assembly for a file
src/HttpSender.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/src/HttpSender.cpp.s
.PHONY : src/HttpSender.cpp.s

src/KafkaConsumer.o: src/KafkaConsumer.cpp.o
.PHONY : src/KafkaConsumer.o

# target to build an object file
src/KafkaConsumer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/src/KafkaConsumer.cpp.o
.PHONY : src/KafkaConsumer.cpp.o

src/KafkaConsumer.i: src/KafkaConsumer.cpp.i
.PHONY : src/KafkaConsumer.i

# target to preprocess a source file
src/KafkaConsumer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/src/KafkaConsumer.cpp.i
.PHONY : src/KafkaConsumer.cpp.i

src/KafkaConsumer.s: src/KafkaConsumer.cpp.s
.PHONY : src/KafkaConsumer.s

# target to generate assembly for a file
src/KafkaConsumer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/src/KafkaConsumer.cpp.s
.PHONY : src/KafkaConsumer.cpp.s

src/KafkaHandler.o: src/KafkaHandler.cpp.o
.PHONY : src/KafkaHandler.o

# target to build an object file
src/KafkaHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/src/KafkaHandler.cpp.o
.PHONY : src/KafkaHandler.cpp.o

src/KafkaHandler.i: src/KafkaHandler.cpp.i
.PHONY : src/KafkaHandler.i

# target to preprocess a source file
src/KafkaHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/src/KafkaHandler.cpp.i
.PHONY : src/KafkaHandler.cpp.i

src/KafkaHandler.s: src/KafkaHandler.cpp.s
.PHONY : src/KafkaHandler.s

# target to generate assembly for a file
src/KafkaHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/src/KafkaHandler.cpp.s
.PHONY : src/KafkaHandler.cpp.s

src/OutputHandler.o: src/OutputHandler.cpp.o
.PHONY : src/OutputHandler.o

# target to build an object file
src/OutputHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/src/OutputHandler.cpp.o
.PHONY : src/OutputHandler.cpp.o

src/OutputHandler.i: src/OutputHandler.cpp.i
.PHONY : src/OutputHandler.i

# target to preprocess a source file
src/OutputHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/src/OutputHandler.cpp.i
.PHONY : src/OutputHandler.cpp.i

src/OutputHandler.s: src/OutputHandler.cpp.s
.PHONY : src/OutputHandler.s

# target to generate assembly for a file
src/OutputHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/src/OutputHandler.cpp.s
.PHONY : src/OutputHandler.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anonymizer.dir/build.make CMakeFiles/anonymizer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... anonymizer"
	@echo "... compiled/http_log.capnp.o"
	@echo "... compiled/http_log.capnp.i"
	@echo "... compiled/http_log.capnp.s"
	@echo "... src/HttpLog.o"
	@echo "... src/HttpLog.i"
	@echo "... src/HttpLog.s"
	@echo "... src/HttpSender.o"
	@echo "... src/HttpSender.i"
	@echo "... src/HttpSender.s"
	@echo "... src/KafkaConsumer.o"
	@echo "... src/KafkaConsumer.i"
	@echo "... src/KafkaConsumer.s"
	@echo "... src/KafkaHandler.o"
	@echo "... src/KafkaHandler.i"
	@echo "... src/KafkaHandler.s"
	@echo "... src/OutputHandler.o"
	@echo "... src/OutputHandler.i"
	@echo "... src/OutputHandler.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

